version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: moar-db
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
    volumes:
      - 'dbdata:/var/lib/postgresql/data'
  api:
    build: .
    image: moar-api
    container_name: moar-api
    ports:
      - 3000:3000
    depends_on:
      - db
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - .:/app
volumes:
  dbdata: